
version: '2'
services:
    api:
        image: screwdrivercd/screwdriver:stable
        ports:
            - 9001:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - ./data/:/tmp/sd-data/:rw
        environment:
            PORT: 80
            URI: http://192.168.97.73:9001
            ECOSYSTEM_UI: http://192.168.97.73:9000
            ECOSYSTEM_STORE: http://192.168.97.73:9002
            SCM_PLUGIN: github
            DATASTORE_PLUGIN: sequelize
            DATASTORE_SEQUELIZE_DIALECT: sqlite
            DATASTORE_SEQUELIZE_STORAGE: /tmp/sd-data/storage.db
            EXECUTOR_PLUGIN: docker
            SECRET_WHITELIST: "[]"
            EXECUTOR_DOCKER_DOCKER: |
                {
                    "socketPath": "/var/run/docker.sock"
                }
            SECRET_OAUTH_CLIENT_ID: eeb684b6c413b2420641
            SECRET_OAUTH_CLIENT_SECRET: 2dd5d8e3d06717ea7821bee450978762fdced6dd
            SECRET_JWT_PRIVATE_KEY: |
                -----BEGIN RSA PRIVATE KEY-----
                MIICXQIBAAKBgQDANvNBx1lieVghVZuRX+0uGC6HCGhwnSTTuRkfrrE7nLd5+rOq
                SCqfJXKlK5+wHLLC+/lVbAuoYhwVfZ6il8DE2EDXv8Ebg6s45NwM5koe1IDyyyYt
                F+wnXOGU0o1KKkPX1dqpv4IAqM8fjimzv/ZjdSVIbSQaiCHoa71YoDGjJwIDAQAB
                AoGAHNkicUDmHW1w2K/shUkMY9qlQQb2BdDP8ibZqnOhjfzbXKdPx8LFAtWv+zIs
                6VWlTrZamYN5zG/NHzyXTnfQKnhfag7LSOi7nC+22tXlfxF5YRcQ/Y+r0boA68n/
                BarAlBc1j4sf3z/xS0Eo8P4NVJYOQ60kHR+BBzig/6SV0aECQQDjQ8zAnHZG6J2r
                8U1IJtQsykh+fJfqRwjHQNyveQvSEfWZLLBafJ5QmoI6HF8XuJZoU1IjPeQqjbyW
                p21DEMczAkEA2IShr8dE1V45ERGeSKg2LDsF5v/fE8pagLzIF/h0pHJ13eYe2v1p
                AyK6n2uzNn7nTRWWNopvUnzHvffTRhUkPQJAYDVzmJaj+6C+HuwoK0NEzzFTPzi/
                lw47SR7MTfyQZH312sJwZd4bp0PBnZglKYWbJs8fFow860bVb3Gxb5LKwQJBANMd
                0AHzTPy3WPF5ulqiGeBa1NB+oWdMoZ5xdLFaw3EtYhwxq9hfyysRi+KyQxZZ+vLA
                n60iopVNsf1bThhBuQkCQQDAg2HQ+1HV1NCRaIrirm6f+q5nzhVLTpKB+YzdiB4n
                XCswmzfRacUnI+0DXGRJ0qp9rVEWK2leEf8/AbH2Rbsh
                -----END RSA PRIVATE KEY-----
            SECRET_JWT_PUBLIC_KEY: |
                -----BEGIN PUBLIC KEY-----
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDANvNBx1lieVghVZuRX+0uGC6H
                CGhwnSTTuRkfrrE7nLd5+rOqSCqfJXKlK5+wHLLC+/lVbAuoYhwVfZ6il8DE2EDX
                v8Ebg6s45NwM5koe1IDyyyYtF+wnXOGU0o1KKkPX1dqpv4IAqM8fjimzv/ZjdSVI
                bSQaiCHoa71YoDGjJwIDAQAB
                -----END PUBLIC KEY-----
    ui:
        image: screwdrivercd/ui:stable
        ports:
            - 9000:80
        environment:
            ECOSYSTEM_API: http://192.168.97.73:9001
            ECOSYSTEM_STORE: http://192.168.97.73:9002

    store:
        image: screwdrivercd/store:stable
        ports:
            - 9002:80
        environment:
            ECOSYSTEM_UI: http://192.168.97.73:9000
            URI: http://192.168.97.73:9002
            SECRET_JWT_PUBLIC_KEY: |
                -----BEGIN PUBLIC KEY-----
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDANvNBx1lieVghVZuRX+0uGC6H
                CGhwnSTTuRkfrrE7nLd5+rOqSCqfJXKlK5+wHLLC+/lVbAuoYhwVfZ6il8DE2EDX
                v8Ebg6s45NwM5koe1IDyyyYtF+wnXOGU0o1KKkPX1dqpv4IAqM8fjimzv/ZjdSVI
                bSQaiCHoa71YoDGjJwIDAQAB
                -----END PUBLIC KEY-----
