
version: '2'
services:
    api:
        image: screwdrivercd/screwdriver:stable
        ports:
            - 9001:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:rw
            - ./data/:/tmp/sd-data/:rw
        environment:
            PORT: 80
            URI: http://192.168.97.73:9001
            ECOSYSTEM_UI: http://192.168.97.73:9000
            ECOSYSTEM_STORE: http://192.168.97.73:9002
            SCM_PLUGIN: github
            DATASTORE_PLUGIN: sequelize
            DATASTORE_SEQUELIZE_DIALECT: sqlite
            DATASTORE_SEQUELIZE_STORAGE: /tmp/sd-data/storage.db
            EXECUTOR_PLUGIN: docker
            SECRET_WHITELIST: "[]"
            EXECUTOR_DOCKER_DOCKER: |
                {
                    "socketPath": "/var/run/docker.sock"
                }
            SECRET_OAUTH_CLIENT_ID: 
            SECRET_OAUTH_CLIENT_SECRET: 
            SECRET_JWT_PRIVATE_KEY: |
                -----BEGIN RSA PRIVATE KEY-----
                MIICXAIBAAKBgQC+Yl6y4qj61N7AyG7dLJaoCb3plhYek+uvTWK4Wtt9g6cNvVeL
                G62peQPD3s4CE9CQmt9DLxu2aDanfQ8OWHMoZxqp8v+brf4gaydteyuIvE7G3gMP
                lUBwp9anSIcMR42gLCziu0BJ/iN2w37DHeSUeTDHmzdEfnV9d1reTZ3xtwIDAQAB
                AoGAHVKtX0QF3sxWmr7ERJCPi8YkWAvj0EXcMR3sLJTh5Y0Xd8hH6YcT0lxvNgXl
                GPDQWNVhuclRrWCTumxKm10IL1ZboSHX/ZHCPB72RLYJriy4heCKy7ADPKdPTVLQ
                2ZHSrL+mdd5HsOojFuEZ19SkW3j0KjEe8gZgtDg6WK2DQ8ECQQD5xXZuHP5QnW9a
                FMpbmy3P7lUzNTpy9xTOc6s3xLXmHutFmXCLg0nq+dEwyf6xiBUuWlgU7qbQUY4O
                os5bZpcxAkEAwyHH5dbpm6u23pflNTZ34ElzhFa6iNNPGpEtaojoszEqNxf/e4eo
                7876h5RU3uO47m3dtqUOJpbo15XnERutZwJBAJA4tsOqNiayYWOwcZAnsHJJ+iRR
                beiIRxlWrNzM1wODgvJzQQstyfbGPUZgvJIiM6jKPeYIT4YmMVK+K02XlWECQFp0
                UmHtGiWbmA3fg9UDBtbltbLnMVkz+ztpiRAVnylR5Svc6AWvgVSJMgGfdShNj/CW
                5WxBXynsUst9Jbv8hIkCQCoXoIeRFTMhUvJLvNEjWLJ8ecfKo2XxB41QxIoPqTe2
                g2sF6pKM5nncJR/W+fiodP0ZCcsEZ6l4lmUqMjgXXPk=
                -----END RSA PRIVATE KEY-----
            SECRET_JWT_PUBLIC_KEY: |
                -----BEGIN PUBLIC KEY-----
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+Yl6y4qj61N7AyG7dLJaoCb3p
                lhYek+uvTWK4Wtt9g6cNvVeLG62peQPD3s4CE9CQmt9DLxu2aDanfQ8OWHMoZxqp
                8v+brf4gaydteyuIvE7G3gMPlUBwp9anSIcMR42gLCziu0BJ/iN2w37DHeSUeTDH
                mzdEfnV9d1reTZ3xtwIDAQAB
                -----END PUBLIC KEY-----
    ui:
        image: screwdrivercd/ui:stable
        ports:
            - 9000:80
        environment:
            ECOSYSTEM_API: http://192.168.97.73:9001
            ECOSYSTEM_STORE: http://192.168.97.73:9002

    store:
        image: screwdrivercd/store:stable
        ports:
            - 9002:80
        environment:
            ECOSYSTEM_UI: http://192.168.97.73:9000
            URI: http://192.168.97.73:9002
            SECRET_JWT_PUBLIC_KEY: |
                -----BEGIN PUBLIC KEY-----
                MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC+Yl6y4qj61N7AyG7dLJaoCb3p
                lhYek+uvTWK4Wtt9g6cNvVeLG62peQPD3s4CE9CQmt9DLxu2aDanfQ8OWHMoZxqp
                8v+brf4gaydteyuIvE7G3gMPlUBwp9anSIcMR42gLCziu0BJ/iN2w37DHeSUeTDH
                mzdEfnV9d1reTZ3xtwIDAQAB
                -----END PUBLIC KEY-----
