workflow:
        - publish

shared:
        image: node:6

jobs:
        main:
                steps:
                        - export: echo hello 
        
        publish:
                steps:
                        - test: echo world

